### ISSUE TITLE
'at ☸️ commerce/api-starter-us-west-1-openshift-com' value appears in my hyper

### ISSUE THREAD

**Issue by anushkamds** [denysdovhan/dotfiles#15]
This kind of thing appear in my terminal after install this
Can you resolve this kind of suck looking at it 
<img width="704" alt="screen shot 2017-10-07 at 12 00 13 am" src="https://user-images.githubusercontent.com/1327120/31292838-8a33f9b2-aaf2-11e7-8413-c26c955578c7.png">

**Comment by denysdovhan** [comment]
I can't fix this, since it's not a bug. It's a part of Spaceship ZSH prompt. `commerce/api-starter-us-west-1-openshift-com` is a Kubectl context. [**Read more here.**](https://github.com/denysdovhan/spaceship-zsh-theme#kubectl-context-kubecontext)
