### ISSUE TITLE
How to get That 'via Node version text'

### ISSUE THREAD

**Issue by Ayanrocks** [denysdovhan/dotfiles#18]
i have hyper and zsh installed with spaceship-zsh. How to get that via the node version text in the terminal?

**Comment by denysdovhan** [comment]
As it said in Spaceship's docs:

> Node.js section is shown only in directories that contain `package.json` file, or `node_modules` folder, or any other file with `.js` extension.
>
> — https://denysdovhan.com/spaceship-prompt/docs/Options.html#nodejs-node
