### ISSUE TITLE
Custom settings into ~/.zshlocal. doesn't work

### ISSUE THREAD

**Issue by hugobrilhante** [denysdovhan/dotfiles#27]
I would like to extend my plugins with docker-compose for example but when I tried to do that it didn't work.

```
# ~/.zshlocal.

plugins = (docker-compose)

```

Am I doing something wrong? Could you help me with this by providing an example?

**Comment by denysdovhan** [comment]
What I see from the example you've provided, you are using invalid syntax.  `.zshlocal` is a zsh file, so you should use zsh syntax in there.

**Comment by hugobrilhante** [comment]
@denysdovhan Sorry for the bad example that made you close the issue. I'll try to explain better. The following example works when it's in `.zshrc` but when I add it the same example in `.zshlocal` doesn't work.

```zsh
# Plugins
plugins=(
   history-substring-search
   git
   npm
   yarn
   nvm
   sudo
   extract
   ssh-agent
   gpg-agent
   macos
   gh
   vscode
   common-aliases
   command-not-found
   docker
   docker-compose
)
```
