### ISSUE TITLE
Sheldon - changed config dir, defer

### ISSUE THREAD

**Issue by andreaspoletti** [denysdovhan/dotfiles#28]
Looks like Sheldon is complaining about some stuff in its latest update and completely breaks the setup (right after updating Sheldon):
1. It changed the config dir from ~/.sheldon to ~/.config/sheldon
2. Defer now has different syntax:

Old:
```
defer = { value = 'zsh-defer source "{{ file }}"', each = true }
```
New:
```
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"
```

Solution:
- add new symlink to dotbot
- change defer

I could submit a PR with the proposed fixes :smile:

**Comment by denysdovhan** [comment]
Thanks! I've fixed that!
