### ISSUE TITLE
brew bundle fails during bootstrap

### ISSUE THREAD

**Issue by ktavabi** [denysdovhan/dotfiles#29]
Happy to report that installation on recent setup went off without a hitch! 🚀 

But I ran into an issue with `brew bundle` during bootstrapping [here](https://github.com/denysdovhan/dotfiles/blob/b950d6a6d316aee900fcfb67dd45019c364c55f8/scripts/bootstrap#L165) because brew is not available in `PATH` for the current shell session. I worked around it by adding `source ~/.zshrc` [here](https://github.com/denysdovhan/dotfiles/blob/b950d6a6d316aee900fcfb67dd45019c364c55f8/scripts/bootstrap#L81). However, according to instructions for Homebrew after installation we should add `brew` to `PATH` by (a) echo `eval "$(/opt/homebrew/bin/brew shellenv)" >> /~.zprofile` and (b) `eval "$(/opt/homebrew/bin/brew shellenv)"`.  Option b [here](https://github.com/denysdovhan/dotfiles/blob/b950d6a6d316aee900fcfb67dd45019c364c55f8/scripts/bootstrap#L81) should fix this issue irrespective of whether `/~.zprofile` exists.
Happy to submit PR as soon as I am setup.

**Comment by denysdovhan** [comment]
We just probably need to add `.zprofile` file under `home` directory, so it can be linked automatically upon installation.

**Comment by ktavabi** [comment]
My understanding is that not everyone uses a `.zprofile` but as it turns out, just injecting `brew` into the path via `eval "$(/opt/homebrew/bin/brew shellenv)"` at runtime fixes this issue. I had a chance to test this on a new build attempt. I haven't been able to open a PR because of GH permissions.
