### ISSUE TITLE
Remove "alias tip"

### ISSUE THREAD

**Issue by dnishiyama** [denysdovhan/dotfiles#37]
This repo is great! I've just noticed one thing that has been bugging me

When I'm using it I get a lot of "Alias tip"s. The most confusing one is 
```
➜ update
Alias tip: update
```

Is there any way to turn these off? I can't find the source of what is generating them.

Thank you!

**Comment by denysdovhan** [comment]
They come from here: https://github.com/denysdovhan/dotfiles/blob/master/home/.zshrc#L138

I don't exactly know how to remove it for you specifically. You can try removing `_alias_tips__preexec` from you precmd functions like this in you custom configuration under `custom` folder. It would not run, but it would still be loaded by zgen.

```
preexec_functions=(${precmd_functions:#_alias_tips__preexec})
```

**Comment by dnishiyama** [comment]
Thank you very much!

**Comment by dnishiyama** [comment]
wow I cannot believe I missed that. I just commented out the zgen command `zgen load djui/alias-tips` and they are removed. Thanks!
